version: '3.7'


services:
  db:
    image: postgres:13-alpine
    restart: always
    container_name: db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1331"
      POSTGRES_DB: "car_rental_db"
    ports:
      - '5432:5432'

volumes:
    postgres_data:
