version: '3.7'


services:
  db:
    image: postgres:13-alpine
    restart: always
    container_name: db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1331"
      POSTGRES_DB: "car_rental_db"
    ports:
      - '5432:5432'

  minio:
    container_name: minio
    image: quay.io/minio/minio
    restart: always
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"


volumes:
    postgres_data:
    minio_data:
